apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: up-and-down-the-river
  name: up-and-down-the-river
spec:
  replicas: 1
  selector:
    matchLabels:
      component: up-and-down-the-river
  template:
    metadata:
      labels:
        component: up-and-down-the-river
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "5932"
    spec:
      volumes:
        - name: up-and-down-the-river-config
          configMap:
            name: up-and-down-the-river-config
      containers:
        - image: docker.io/mfenwick100/upanddowntheriver:$IMAGE_TAG
          imagePullPolicy: Always
          name: up-and-down-the-river
          command:
            - ./server
          args:
            - /etc/up-and-down-the-river/conf.json
          volumeMounts:
            - mountPath: /etc/up-and-down-the-river
              name: up-and-down-the-river-config
          ports:
            - containerPort: 5932
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: up-and-down-the-river
  name: up-and-down-the-river
spec:
  ports:
    - port: 5932
  selector:
    component: up-and-down-the-river
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: up-and-down-the-river-config
data:
  conf.json: |
    {
      "UIDirectory": "/tmp/ui/",
      "LogLevel": "debug",
      "Port": 5932
    }
